# Site
repository: My resume in this git repository 


# Personal info
name: Shreekant Kembhavi
title: DevOps Engineer
email: shreekant.pk@gmail.com
website: https://shree.uk/

darkmode: false

# Social links
linkedin_username: shreekantpk
facebook_username: shreekantpk
twitter_username: shreekantpk
instagram_username: shreekantpk
# github_username:  shreekantpk
# stackoverflow_username: "1285684"
# dribbble_username: shreekantpk
# flickr_username: shreekantpk
# xing_username: shreekantpk
# pinterest_username: shreekantpk
# youtube_username: shreekantpk
# googleplus_username: +shreekantpk
# orcid_username: 0000-0000-0000-0000

# Social links for footer
footer_linkedin_username: shreekantpk
footer_facebook_username: shreekantpk
footer_twitter_username: shreekantpk
footer_instagram_username: shreekantpk
#footer_github_username:  shreekant
footer_stackoverflow_username: "1285684"
footer_dribbble_username: shreekantpk
#footer_flickr_username: shreekant.pk
#footer_xing_username: shreekantpk
footer_pinterest_username: shreekantpk
footer_youtube_username: shreekantpk
# footer_googleplus_username: +shreekantpk
# footer_orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Download CV
  icon: fas fa-arrow-alt-circle-down
  url: ./doc/Resume.pdf
# - title: 
#   icon: 
#   url: 


#Google Analytics and Tag Manager
gtm: "GTM-M45TT4T"
gtag: "UA-162149612-1"
google_analytics: "UA-162149612-1"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: doc/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I am DevOps Specialist with over 7 years of professional experience and has developed a range of skills across MultiCloud environment with DevOps, software development, cloud computing, Linux and more. I have been working as <mark>DevOps Engineer</mark> since beginning of my career.
  
  Currently working at Accenture UK as DevOps Specialist, prior to which I worked as DevOps Engineer at SAP Labs, Oracle and Cisco. I have worked for multiple projects including IoT, digital supply chain & manufacturing, oracle HCM Cloud and set top boxes.

  Alongside, I am Certified in Azure and AWS, also have 7 years of strong computer science education background including masters degree in Information Technology from The University of Nottingham, United Kingdom. 
  
#  Feel free to get in touch for <mark>DevOps consultation</mark> and <mark>freelancing.</mark> 

  
# Certifications Section
# certifications_title: Certifications #(Use this to override about certifications section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Besides my professional life, I am fond of travel, food and growing my network 😊
  
  **Like people often say motivation doesn’t last. Well, neither does bathing—that’s why we recommend it daily.** 

  Stay motivated and get in touch with on [LinkedIn](https://www.linkedin.com/in/shreekantpk/) or [email me](mailto:shreekant.pk@gmail.com) to stay connected!

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
